// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gltfEngine.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Com.Gltf.Grpc {
  public static class GltfService
  {
    static readonly string __ServiceName = "com.gltf.grpc.GltfService";

    static readonly Marshaller<global::Com.Gltf.Grpc.GltfModel> __Marshaller_GltfModel = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Gltf.Grpc.GltfModel.Parser.ParseFrom);
    static readonly Marshaller<global::Com.Common.Grpc.RpcVoid> __Marshaller_RpcVoid = Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Common.Grpc.RpcVoid.Parser.ParseFrom);

    static readonly Method<global::Com.Gltf.Grpc.GltfModel, global::Com.Common.Grpc.RpcVoid> __Method_check = new Method<global::Com.Gltf.Grpc.GltfModel, global::Com.Common.Grpc.RpcVoid>(
        MethodType.Unary,
        __ServiceName,
        "check",
        __Marshaller_GltfModel,
        __Marshaller_RpcVoid);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Gltf.Grpc.GltfEngineReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GltfService</summary>
    public abstract class GltfServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Com.Common.Grpc.RpcVoid> check(global::Com.Gltf.Grpc.GltfModel request, ServerCallContext context)
      {
        throw new RpcException(new Status(StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GltfService</summary>
    public class GltfServiceClient : ClientBase<GltfServiceClient>
    {
      /// <summary>Creates a new client for GltfService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GltfServiceClient(Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GltfService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GltfServiceClient(CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GltfServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GltfServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Com.Common.Grpc.RpcVoid check(global::Com.Gltf.Grpc.GltfModel request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return check(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Com.Common.Grpc.RpcVoid check(global::Com.Gltf.Grpc.GltfModel request, CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_check, null, options, request);
      }
      public virtual AsyncUnaryCall<global::Com.Common.Grpc.RpcVoid> checkAsync(global::Com.Gltf.Grpc.GltfModel request, Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return checkAsync(request, new CallOptions(headers, deadline, cancellationToken));
      }
      public virtual AsyncUnaryCall<global::Com.Common.Grpc.RpcVoid> checkAsync(global::Com.Gltf.Grpc.GltfModel request, CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_check, null, options, request);
      }
      protected override GltfServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GltfServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    public static ServerServiceDefinition BindService(GltfServiceBase serviceImpl)
    {
      return ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_check, serviceImpl.check).Build();
    }

  }
}
#endregion
